### ISSUE TITLE
LoadError (cannot load such file -- byebug)

### ISSUE THREAD

**Issue by yuhui** [ombulabs/harvesting#6]
After installing the gem as described in README, the gem cannot run without byebug.

Traceback
```
[snip]
        4: from /Users/user/.rvm/gems/ruby-2.5.2@gemset/gems/harvesting-0.1.0/lib/harvesting.rb:14:in `<top (required)>'
        3: from /Users/user/.rvm/gems/ruby-2.5.2@gemset/gems/harvesting-0.1.0/lib/harvesting.rb:14:in `require'
        2: from /Users/user/.rvm/gems/ruby-2.5.2@gemset/gems/harvesting-0.1.0/lib/harvesting/client.rb:3:in `<top (required)>'
        1: from /Users/user/.rvm/gems/ruby-2.5.2@gemset/gems/harvesting-0.1.0/lib/harvesting/client.rb:3:in `require'
LoadError (cannot load such file -- byebug)
```

**Comment by etagwerker** [comment]
@yuhui Thanks for reporting this! 

I just pushed version 0.2.0 which should have a fix for it. Please test with that version and let us know.

**Comment by yuhui** [comment]
Works now, thanks
